### ISSUE TITLE
IMU alignment unclear

### ISSUE THREAD

**Issue by deniz-hofmeister** [rsasaki0109/graphslam_ros2#21]
Dear @rsasaki0109,

Should I follow the IMU guide given in: [https://github.com/TixiaoShan/LIO-SAM#prepare-imu-data](https://github.com/TixiaoShan/LIO-SAM#prepare-imu-data)?
I ask this since I assume I dont need to prepare the lidar data as such: [https://github.com/TixiaoShan/LIO-SAM#prepare-lidar-data](https://github.com/TixiaoShan/LIO-SAM#prepare-lidar-data) as pointCloud2 data does not carry ring numbers.

I assume that I can simply make sure myself that the axis of the IMU data align with the axis of the lidar? Or should the output of the IMU be identical to the axis of the IMU image? With all the axis modifications as mentioned?

Does the imu data have to contain RAW acceleration data? (incl. gravity) and do i need to compute a covariance matrix? 

Last question: How can it be that the modules start running when I specify use_imu: True at moments when i am not launching the IMU? Shouldnt it wait for imu messages to come in before starting?  

Im not able to get reliable performance yet. It jumps all over the place. But am hopeful.

Greetings and thank you for your time,

Deniz

**Comment by rsasaki0109** [comment]
Thanks for the good issue.

For IMU composites in this package, the lidar data does not need to include ring numbers or time like lio-sam.

Currently, the IMU composite for this package is based on Lego-LOAM. 

Distortion correction by imu
lidar_undistortion.hpp
https://github.com/rsasaki0109/lidarslam_ros2/blob/foxy/scanmatcher/include/scanmatcher/lidar_undistortion.hpp

For imu-compound, you need to change the `scam_period` parameter.
I didn't put it in the readme.md, sorry.
I just updated the README.md file.

If you have trouble getting it to work, I recommend looking at the lego-loam issue.

Examples of lego-loam issues
How to align the IMU to Lidar? && Problems with the KITTI dataset 
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/153
Coordinate transformation when use imu 
https://github.com/RobustFieldAutonomyLab/LeGO-LOAM/issues/19

> I assume that I can simply make sure myself that the axis of the IMU data align with the axis of the lidar? Or should the output of the IMU be identical to the axis of the IMU image? With all the axis modifications as mentioned?

I think the above issues are helpful.

> Does the imu data have to contain RAW acceleration data? (incl. gravity) and do i need to compute a covariance matrix?

Now, the imu message must contain angle velocity, acceleration, and orientation(In other words, it must be a 9-axis IMU.). No covariance is required.

> Last question: How can it be that the modules start running when I specify use_imu: True at moments when i am not launching the IMU? Shouldnt it wait for imu messages to come in before starting?

Because even when the IMU is not launched, the modules of lego-loam start running.
This package uses only IMU for distortion correction and does not use IMU for preintegration, so I don't think it's a problem to start the module before the imu message comes. But some kind of warning statement might be necessary.

**Comment by rsasaki0109** [comment]
Later on I will add a imu demo using the lego-loam dataset, so please be patient.


jackal_dataset_20170608
https://github.com/RobustFieldAutonomyLab/jackal_dataset_20170608

**Comment by rsasaki0109** [comment]
My apologies.
Apparently there was a bug with respect to the IMU, which caused lidar to jump all over the place.

I've just fixed it.

If you set the scan_period to 0.1, it works fine with any of the data in the above dataset.

**Comment by rsasaki0109** [comment]
I close this issue because there is no recent activity on this issue.
Please open the issue again if you have any further problems.

**Comment by mattdouglas-dt** [comment]
good afternoon, I am having a similar issue I believe trying to integrate the bno055 IMU into the codeset. even enabling the IMU in the code still doesn't appear to look at the IMU data, and uses the Lidar only for orientation etc, any help would be greatly appreciated in this.

EDIT: I forgot to add my skillset in ros2 is very limited, but I am managing to see the IMU data in the topics and in RVIZ2 (only able to see the change in RVIZ2 from the IMU when it is assigned to base_link in the bno055 driver).

as I plan on only using the lidarslam indoors, I am hoping to get it more accurate, but otherwise I am very happy with how well it is working on the raspberry pi 5

**Comment by rsasaki0109** [comment]
The IMU is being used here:
https://github.com/rsasaki0109/lidarslam_ros2/blob/develop/scanmatcher/src/scanmatcher_component.cpp#L241-L243

If you want to use the IMU, this might be a better option:
https://github.com/rsasaki0109/li_slam_ros2

The IMU integration in lidarslam_ros2 is based on LEGO LOAM and is a bit lackluster in some respects, so I suggest using the one above.
